version: "3"
services:
 tomcat1:
  image: tanimraja1/c7-systemd-java-tomcat
  container_name: tomcat1
  hostname: tomcat1
 tomcat2:
  image: tanimraja1/c7-systemd-java-tomcat
  container_name: tomcat2
  hostname: tomcat2
 tomcat3:
  image: tanimraja1/c7-systemd-java-tomcat
  container_name: tomcat3
  hostname: tomcat3
 httpd:
  container_name: httpd
  hostname: httpd
  image: tanimraja1/c7-httpd
  ports:
   - "80:80"
   - "443:443"