version: "2"
services:
 tomcat1:
  image: kartish/smappimage:0.0.4
  ports:
   - "8080:8080"
 tomcat2:
  image: tomcat:8.5-alpine
  ports:
   - "8081:8080"
 tomcat3:
  image: tomcat:8.5-alpine
  ports:
   - "8082:8080"